language: node_js
node_js:
  - '14'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - npm test
  - bash deploy.sh

before_deploy:
  - echo "Running before deploy steps"

deploy:
  provider: script
  script: echo "Deploy"
  on:
    branch: master

notifications:
  email: false