language: node_js
node_js:
  - '14'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - npm test
  - bash deploy.sh

before_deploy:
  - echo "Running before deploy steps"
  - echo $GCLOUD_SERVICE_KEY | base64 --decode > /tmp/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
  - gcloud config set project $GCLOUD_PROJECT_ID

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

notifications:
  email: false