language: node_js
node_js:
  - '14'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install --save-dev @babel/plugin-proposal-private-property-in-object
  - npm install --save-dev babel-jest @babel/preset-env @babel/preset-react

script:
  - npm run build
  - npm test

before_deploy:
  - npm run build

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

notifications:
  email: false